# Generated by Django 3.1.4 on 2020-12-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savelink_org',
            name='tags',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
