# Generated by Django 3.1.4 on 2020-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0002_savelink_org_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savelink_org',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
