# Generated by Django 3.1.4 on 2020-12-13 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0003_auto_20201213_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savelink_org',
            name='labels',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savelink_org',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savelink_org',
            name='url',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
