# Generated by Django 3.1.4 on 2020-12-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=250)),
                ('email', models.CharField(default='email', max_length=250)),
                ('pistack', models.TextField(default='Intrests')),
            ],
        ),
    ]
