# Generated by Django 3.1.4 on 2020-12-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
            ],
        ),
    ]
